name: 'Setup Cosmospolitan toolchain'
description:
  'GitHub action to setup Cosmospolitan toolchain on Linux, Windows and macOS.'

inputs:
  version:
    description: 'Cosmospolitan toolchain version'
    required: false
  path:
    description: 'Toolchain path'
    required: false
    default: '.cosmopolitan'
  url:
    description: 'Custom URL for cosmocc zip archive'
    required: false
  github-token:
    description: 'GitHub token for downloading nightly artifacts'
    required: false
    default: ${{ github.token }}

runs:
  using: 'node24'
  main: 'dist/index.js'
